export default {
    list: [
        {
            host: "yfun.top",
            ssl: true,
            port: 443,
            name: "YFun's Home",
            method: "GET",
            ok: "200-299",
        },
        {
            host: "blog.yfun.top",
            ssl: true,
            port: 443,
            name: "YFun's Blog",
            method: "GET",
            ok: "200-299",
        },
        {
            host: "disk.yfun.top",
            ssl: true,
            port: 443,
            name: "CKY Netdisk",
            method: "GET",
            ok: "200-299",
        },
        {
            host: "imcky.top",
            ssl: true,
            port: 443,
            name: "CKY",
            method: "GET",
            ok: "200-299",
        },
        {
            host: "jsd.cky.codes",
            ssl: true,
            port: 443,
            name: "jsDelivr (CKY)",
            method: "GET",
            ok: "200-299",
        },
        {
            host: "gravatar.yfun.top",
            ssl: true,
            port: 443,
            name: "Gravatar (CKY)",
            method: "GET",
            ok: "200-299",
        },
        {
            host: "github.yfun.top",
            ssl: true,
            port: 443,
            name: "GitHub API (CKY)",
            method: "GET",
            ok: "200-299",
        },
    ],
    filedir: "./data/",
    filename: "{{@date}}.json",
    limit: 240,
    node: "GitHub Action",
};
